#!/usr/bin/env python3
"""Build the social-share preview for every paper highlight page.

For each highlights/<slug>.html this script:
  1. renders a 1200x630 card (tools/share-card.html, screenshotted with
     headless Chrome) to highlights/cards/<slug>.png;
  2. writes Open Graph / Twitter Card <meta> tags into the page <head>, so X,
     Bluesky and LinkedIn show that card when the page is shared;
  3. makes sure the page loads js/share-buttons.js (the X / Bluesky / LinkedIn
     buttons).

Re-run it after adding or editing a highlight page:
    python3 tools/share_cards.py
It is safe to run repeatedly; the generated <meta> block is replaced each time.
"""
import base64, hashlib, html, json, os, re, shutil, socket, subprocess, sys, time
from pathlib import Path

SITE = 'https://rpmenezes.github.io'
ROOT = Path(__file__).resolve().parent.parent
HIGHLIGHTS = ROOT / 'highlights'
CARDS = HIGHLIGHTS / 'cards'
META_START = '<!-- share-meta:start (generated by tools/share_cards.py) -->'
META_END = '<!-- share-meta:end -->'
SCRIPT_TAG = '<script src="../js/share-buttons.js"></script>'


def text(fragment):
    """Visible text of an HTML fragment, whitespace collapsed."""
    return re.sub(r'\s+', ' ', html.unescape(re.sub(r'<[^>]+>', '', fragment))).strip()


def first(pattern, source):
    m = re.search(pattern, source, re.S)
    return m.group(1) if m else ''


def read_paper(page):
    src = page.read_text()
    authors_html = first(r'class="hero-authors">(.*?)</p>', src)
    stats = re.findall(r'class="stat-label">(.*?)</span>\s*<span class="stat-value">(.*?)</span>', src, re.S)
    slug = page.stem
    return {
        'slug': slug,
        'url': f'{SITE}/highlights/{slug}.html',
        'meta': text(first(r'class="hero-meta">(.*?)</div>', src)),
        'title': text(first(r'<h1>(.*?)</h1>', src)),
        'authors': [a for a in (s.strip() for s in text(authors_html).split('·')) if a],
        'me': text(first(r'<span class="highlight">(.*?)</span>', authors_html)) or 'Ronaldo Menezes',
        'journal': text(first(r'class="hero-journal">(.*?)</p>', src)),
        'stats': [{'label': text(l), 'value': text(v)} for l, v in stats[:4]],
    }


def short_authors(paper):
    """Same rule as the card: more than four authors -> four names + et al."""
    a, me = paper['authors'], paper['me']
    if len(a) <= 4:
        return ', '.join(a)
    at = a.index(me) if me in a else -1
    shown = a[:3] + ['…', me] if at >= 4 else a[:4]
    return ', '.join(shown) + ' et al.'


def find_chrome():
    for c in [os.environ.get('CHROME'),
              '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
              shutil.which('google-chrome'), shutil.which('chromium'), shutil.which('chromium-browser')]:
        if c and Path(c).exists():
            return c
    sys.exit('Chrome not found; set the CHROME environment variable to its path.')


def free_port():
    with socket.socket() as s:
        s.bind(('127.0.0.1', 0))
        return s.getsockname()[1]


def render_card(chrome, port, paper, out):
    payload = base64.urlsafe_b64encode(json.dumps(paper).encode()).decode()
    url = f'http://127.0.0.1:{port}/tools/share-card.html#{payload}'
    subprocess.run([chrome, '--headless=new', '--disable-gpu', '--hide-scrollbars',
                    '--force-device-scale-factor=1', '--window-size=1200,630',
                    '--virtual-time-budget=3000', f'--screenshot={out}', url],
                   check=True, capture_output=True, timeout=60)


def meta_block(paper, image_url):
    # hero-meta reads "Research Article · <Journal> · Published <date>"
    parts = [p.strip() for p in paper['meta'].split('·')]
    journal = parts[1] if len(parts) > 1 else ''
    desc = ' · '.join(p for p in ['Research highlight', journal, short_authors(paper)] if p)
    e = lambda s: html.escape(s, quote=True)
    rows = [
        f'<meta name="description" content="{e(desc)}">',
        '<meta property="og:type" content="article">',
        '<meta property="og:site_name" content="Ronaldo Menezes">',
        f'<meta property="og:title" content="{e(paper["title"])}">',
        f'<meta property="og:description" content="{e(desc)}">',
        f'<meta property="og:url" content="{e(paper["url"])}">',
        f'<meta property="og:image" content="{e(image_url)}">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="{e(paper["title"])}: research highlight card">',
        '<meta name="twitter:card" content="summary_large_image">',
        f'<meta name="twitter:title" content="{e(paper["title"])}">',
        f'<meta name="twitter:description" content="{e(desc)}">',
        f'<meta name="twitter:image" content="{e(image_url)}">',
    ]
    return '    ' + META_START + '\n' + ''.join(f'    {r}\n' for r in rows) + '    ' + META_END + '\n'


def update_page(page, block):
    src = page.read_text()
    src = re.sub(r'\s*' + re.escape(META_START) + r'.*?' + re.escape(META_END) + r'\n?', '\n', src, flags=re.S)
    src = src.replace('</head>', block + '</head>', 1)
    src = re.sub(r'\s*<script src="\.\./js/share-card\.js"></script>', '', src)   # earlier prototype
    if SCRIPT_TAG not in src:
        src = src.replace('</body>', f'    {SCRIPT_TAG}\n</body>', 1)
    page.write_text(src)


def main():
    chrome = find_chrome()
    CARDS.mkdir(exist_ok=True)
    port = free_port()
    server = subprocess.Popen([sys.executable, '-m', 'http.server', str(port), '--bind', '127.0.0.1'],
                              cwd=ROOT, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        time.sleep(0.8)
        for page in sorted(HIGHLIGHTS.glob('*.html')):
            paper = read_paper(page)
            if not paper['title']:
                print(f'skip {page.name}: no <h1> title found')
                continue
            out = CARDS / f'{paper["slug"]}.png'
            render_card(chrome, port, paper, out)
            # Version the image URL by content so platforms refetch a changed card.
            version = hashlib.sha1(out.read_bytes()).hexdigest()[:8]
            update_page(page, meta_block(paper, f'{SITE}/highlights/cards/{out.name}?v={version}'))
            print(f'ok   {page.name} -> cards/{out.name}')
    finally:
        server.terminate()


if __name__ == '__main__':
    main()
